In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])

In [7]:
arr+10 #broadcasting  : 10 is added to all the element 

array([11, 12, 13, 14])

In [19]:
arr2 =  np.array([10,2,4,3]) # broadcasting a one d array

In [21]:
arr + arr2

array([11,  4,  7,  7])

In [34]:
arr3 = np.array([[10,2,3,11] , [3,4,5,6]])  #broadcasting of 2d array

In [36]:
arr3

array([[10,  2,  3, 11],
       [ 3,  4,  5,  6]])

In [38]:
arr3 +arr2

array([[20,  4,  7, 14],
       [13,  6,  9,  9]])