In [1]:
import numpy as np


In [5]:
!pip install numpy

In [7]:
arr = np.array([1,2,3]) #creating 1D numpy array

In [9]:
arr

array([1, 2, 3])

In [11]:
np.zeros((3,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((2,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
np.full((4,6), 9)

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [27]:
np.full((3,1000),9)

array([[9, 9, 9, ..., 9, 9, 9],
       [9, 9, 9, ..., 9, 9, 9],
       [9, 9, 9, ..., 9, 9, 9]])

In [29]:
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.arange(1,500,100)

array([  1, 101, 201, 301, 401])

In [39]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [49]:
marray = np.array([[2,3,4],[2,3,5],[4,5,7],[2,4,5]])

In [51]:
marray

array([[2, 3, 4],
       [2, 3, 5],
       [4, 5, 7],
       [2, 4, 5]])

In [55]:
type(marray)

numpy.ndarray

In [57]:
np.shape(marray)

(4, 3)

In [59]:
marray.size

12

In [61]:
marray.ndim

2

In [63]:
marray.dtype

dtype('int32')

In [71]:
reshaped = marray.reshape((6,2))

In [73]:
reshaped

array([[2, 3],
       [4, 2],
       [3, 5],
       [4, 5],
       [7, 2],
       [4, 5]])

In [79]:
flat_array = marray.flatten()

In [81]:
flat_array

array([2, 3, 4, 2, 3, 5, 4, 5, 7, 2, 4, 5])