In [7]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])

In [9]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
flat_array = arr.flatten()

In [17]:
flat_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
# indexing 
flat_array[0]

1

In [21]:
flat_array[3:10]

array([ 4,  5,  6,  7,  8,  9, 10])

In [29]:
flat_array[:9] #same as flat_array[0:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
flat_array[4:] #same as flat_array[4:12]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
#prove that changes affect the original array
new_array = flat_array[3:6]

In [54]:
new_array

array([666666,      5,      6])

In [56]:
new_array[0] = 666666

In [58]:
new_array

array([666666,      5,      6])

In [60]:
flat_array #Slicing returns a view not a copy

array([     1,      2,      3, 666666,      5,      6,      7,      8,
            9,     10,     11,     12])

In [63]:
# to create a copy of an array
arr = np.array([2,3,4,5])


In [71]:
flat = arr[0:2].copy()

In [73]:
flat

array([2, 3])

In [75]:
flat[1] = 999

In [77]:
flat

array([  2, 999])

In [79]:
arr

array([2, 3, 4, 5])

In [99]:
#fancy indexing
arr = np.array([1,45,67,88,99,9999,12,88,56,0])

In [101]:
arr

array([   1,   45,   67,   88,   99, 9999,   12,   88,   56,    0])

In [105]:
arr[[1,4,6]]

array([45, 99, 12])

In [109]:
#boolean masking
arr[arr>6]

array([  45,   67,   88,   99, 9999,   12,   88,   56])

In [129]:
#Exercises for practice
arr_1 = np.array([[1.3,2.8,3.9],[3.33,4.4,7.6],[9.1,6.4,4.6]])

In [131]:
arr_1

array([[1.3 , 2.8 , 3.9 ],
       [3.33, 4.4 , 7.6 ],
       [9.1 , 6.4 , 4.6 ]])

In [135]:
arr_1.shape #check the shape

(3, 3)

In [154]:
 arr_1 = arr_1.astype(int) #convert into integer

In [175]:
#find the position of  even element
rows, cols = np.where(arr_1 %  2== 0)
#use fancy indexing
even_num  = arr_1[rows,cols]

In [177]:
even_num

array([2, 4, 6, 4])

In [179]:
reshaped = even_num.reshape(2,2)

In [181]:
reshaped

array([[2, 4],
       [6, 4]])

In [185]:
arr_1[arr_1>4]

array([7, 9, 6])

In [187]:
# using boolean masking
arr_1[arr_1 %2==0]

array([2, 4, 6, 4])