In [1]:
import numpy as np

In [15]:
arr_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr_2[0]

array([1, 2, 3])

In [33]:
np.sum(arr_2 ,axis=1)# axis 1 is the refers to the row

array([ 6, 15, 24])

In [39]:
np.sum(arr_2 , axis=0) # axis 0 is refers to the coloums

array([12, 15, 18])

In [41]:
# indexing in multi-D array
arr_2[0][1]

2

In [55]:
arr[0:2 , 1:3] # indexing row and col.

array([[2, 3],
       [5, 6]])

In [57]:
arr_2[1:3 , 0:2]

array([[4, 5],
       [7, 8]])

In [73]:
# creating 3-D array
arr_3 = np.array([[[1,2,3],[4,5,6]],[[8,9,10],[9,4,5]]])

In [75]:
arr_3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [ 9,  4,  5]]])

In [79]:
arr_3.shape #output is (depth(sheets of data) , rows, columns)

(2, 2, 3)

In [81]:
arr_3[1,1,1]

4

In [85]:
arr_3[: ,0,:] # every sheet of data + 0th row + every column

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [88]:
# changinf data along axis
# replace all element in column 1 with 0
arr_3[:,1,:] =0



In [90]:
arr_3

array([[[ 1,  2,  3],
        [ 0,  0,  0]],

       [[ 8,  9, 10],
        [ 0,  0,  0]]])